name: Deploy Laravel to Azure VM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan queue:restart
            sudo systemctl restart apache2
          EOF
